config/routes.rb
HomeschoolHomeroom::Application.routes.draw do

  devise_for :users
  root to: "home#index"

  resources :groups, only: [:index, :show, :new, :create]
  resources :memberships, only: [:new, :create]

  resources :groups do
    resources :topics, only: [:new, :create]
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  validates_presence_of :organizer_id
  validates_presence_of :name
  validates_presence_of :location
  validates_presence_of :description

  validates_uniqueness_of :name

  belongs_to :organizer, class_name: 'User', foreign_key: 'organizer_id'
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships, foreign_key: 'member_id'
  has_many :topics, dependent: :destroy
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  validates_presence_of :member_id
  validates_presence_of :group_id

  belongs_to :member, class_name: 'User', foreign_key: 'member_id'
  belongs_to :group
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates_presence_of :author_id
  validates_presence_of :group_id
  validates_presence_of :name
  validates_presence_of :description

  belongs_to :group
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :email
  validates_presence_of :password

  has_many :memberships, foreign_key: 'member_id', dependent: :destroy
  has_many :groups, through: :memberships
  has_many :topics, foreign_key: 'author_id'

  def name
    "#{first_name} #{last_name}"
  end

  def is_member_of(group)
    membership = Membership.where(member: self, group: group)
    if membership.empty?
      false
    else
      true
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name, :interests]
  end

  def after_sign_in_path_for(resource)
    groups_path
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    unless current_user.is_member_of(@group)
      redirect_to groups_path, notice: "You must be a member to view a group's profile."
    end
    session[:group_id] = @group.id
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to group_path(@group), notice: 'Success!'
    else
      flash[:notice] = "Sorry, we encountered a problem."
      redirect_to 'new'
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :description, :location).merge(organizer: current_user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index

  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  def create
    @group = Group.find(params[:group_id])
    @membership = Membership.new(member: current_user, group: @group)
    if @membership.save
      redirect_to group_path(@group), notice: "Welcome to #{@group.name}!"
    else
      flash.now[:notice] = "Sorry, we encountered an error."
      redirect_to groups_path
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def new
    @group = Group.find(params[:group_id])
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      redirect_to group_path(@topic.group), notice: "Your topic was posted!"
    else
      flash[:notice] = "Uh oh! We encountered a problem."
      redirect_to groups_path
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:name, :description).merge(author_id: current_user.id).merge(group_id: params[:group_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/index.html.erb
<div class="row">
  <div class="large-8 small-12 columns large-centered">
    <div class="content">
      <h1>All Groups</h1>

      <p><%= link_to 'Add Group', new_group_path %></p>

      <table>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Location</th>
        </tr>

      <% @groups.each do |group| %>
        <tr>
          <td><%= group.name %></td>
          <td><%= group.description %></td>
          <td><%= group.location %></td>
          <% unless current_user.is_member_of(group) %>
            <td><%= button_to 'Join', {controller: :memberships, action: :create, group_id: group.id }, class: 'button tiny' %></td>
          <% else %>
            <td><%= link_to 'Profile', group_path(group) %></td>
          <% end %>
        </tr>
      <% end %>

      </table>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<h2>Add group</h2>

<%= simple_form_for @group do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :location %>
  <%= f.submit 'Create Group' %>
<% end %>

app/views/groups/show.html.erb
<div class="row">
  <div class="large-8 small-12 columns large-centered">
    <div class="content">

      <h2>Group Profile</h2>
      <div>
        <p>Name: <%= @group.name %></p>
        <p>Description: <%= @group.description %></p>
        <p>Organizer: <%= @group.organizer.name %></p>
        <p>Location: <%= @group.location %></p>
      </div>

      <p><%= button_to 'Propose a lesson topic', { controller: :topics, action: :new, group_id: @group.id, author_id: current_user.id }, method: :get, class: 'button' %></p>
    </div>
  </div>
</div>

<% if !@group.topics.blank? %>
  <div class="row">
    <div class="large-8 small-12 columns large-centered">
      <div class="content">
        <table>
          <tr>
            <th>Date</th>
            <th>Name</th>
            <th>Description</th>
            <th>Posted by</th>
          </tr>

          <% @group.topics.each do |topic| %>
          <tr>
            <td><%= topic.created_at %></td>
            <td><%= topic.name %></td>
            <td><%= topic.description %></td>
            <td><%= topic.author.name %></td>
          </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<div class="row">
  <div class="large-8 small-12 columns large-centered">
    <div class="content centered">
      <h1>Welcome to Homeschool Homeroom!</h1>
      <p> Homeschool Homeroom helps homeschooling groups to plan lessons on topics that interest their students.</p>

      <p>Students can propose topics that they want to learn about which their peers can upvote, allowing parents and teachers to gauge interest.  Others in the group who have some knowledge of that topic can then claim it and schedule it using Google calendars.</p>
    <p>
      This app was created by <%= link_to 'Helen Hood', 'http://www.linkedin.com/in/helenhood', target: '_blank' %>, an apprentice developer at <%= link_to 'Launch Academy', 'http://www.launchacademy.com/', target: '_blank' %>, as part of Launch's inaugural "Ship It Saturday" hackathon.  It is currently in its alpha stages and will be developed further in the coming weeks.  If you have any comments or suggestions, please <%= link_to 'Tweet at Helen', 'https://twitter.com/hchood', target: '_blank' %>.  Thanks!
    </p>
  </div>

  <div class="row">
    <% if !current_user %>
      <div class="large-3 small-6 content">
        <%= link_to 'Sign Up', new_user_registration_path %>
      </div>
      <div class="large-3 small-6 content">
        <%= link_to 'Sign In', new_user_session_path %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Welcome to Homeschool Homeroom!" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>



    <div class="row">
      <div class="large-8 small-12 columns large-centered">
        <div class="content">
          <% if current_user %>
            <ul class="horizontal">
              <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
              <li><%= link_to 'View Groups', groups_path %></li>
            </ul>
          <% end %>
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>
      </div>
    </div>

    <%= yield %>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/topics/new.html.erb
<div class="row">
  <div class="large-8 small-12 columns large-centered">
    <div class="content">

      <h2>Post a new lesson topic</h2>

      <div>
        <%= form_for [@group, @topic] do |f| %>
          <%= f.label :name, 'Name' %>
          <%= f.text_field :name %>
          <%= f.label :description, 'Description' %>
          <%= f.text_area :description %>
          <%= f.submit "Post Topic", class: "button"  %>
        <% end %>
      </div>
    </div>
  </div>
</div>